language: node_js

node_js:
  - "6"
  - "8"

addons:
  apt:
    packages:
      - libcairo2-dev
      - libgif-dev
      - libjpeg-dev
      - libpng-dev

env:
  # Run each sub-folder separately in the build matrix
  - TEST_DIR=client
  - TEST_DIR=server

install:
  - ./setup.sh
  - cd $TEST_DIR
  - npm install

script:
  - npm test
